### ISSUE TITLE
US-020 Design Figma prototype for heatmap

### ISSUE THREAD

**Issue by Palpat3** [willayy/DAT257-Agile#37]
***As a developer I want to know how the heatmap I am implementing should work***

### Because

developing without a clear goal is time-inefficient and prone to different  design from the rest of the project

### Tasks

- [x] Create a design for the heatmap that follows the layout of the project.
~- [ ] Create an interactable page in Figma for the heatmap.~

### Acceptance criteria

- There exists a figma page that explains how the heatmap should work
- The heatmap follows the layout of the rest of the project.

**Comment by willayy** [comment]
Removed task to create interactive sketch because it isnt needed to reachdefinition of done

**Comment by willayy** [comment]
@jmarkusson @Palpat3 @maxdreifeldt @Aoc67310 @0-Gixty-0 Ny heatmap finns [här](https://www.figma.com/file/pHVNps7HhKxviBVArfayZr/first-draft?type=design&node-id=0-1&mode=design&t=KolyKaDyMCuJhVQ6-0)
