### ISSUE TITLE
US-005 Create crime location combo box

### ISSUE THREAD

**Issue by willayy** [willayy/DAT257-Agile#6]
As a user I want a filter combo box where I can select "Kommuner & Län" 

### Because
I want to see data from my own area

### Tasks

- [ ] Create a react combo box component that has a drop down menu with "Kommuner & Län" and a search bar where you can search "Kommuner & Län" by name.
- [ ] Create a simple CSS document for the component style.

### Acceptance criteria
There should be a visible combo box on the web app

**Comment by maxdreifeldt** [comment]
This has been done in pull request #20
